### PR TITLE
Block packages with illegal package dependency version ranges

### LINKED ISSUE #3482: feed2catalog produces catalog items with invalid dependency version ranges
V3 registration blobs contain packages with invalid version ranges

https://api.nuget.org/v3/registration1/nservicebus.persistence.sql.msbuild/index.json

### Expected

feeds should validate packages and avoid displaying invalid data in the feed

### Actual

From the client
``install-package nservicebus.persistence.sql.msbuild -version 1.0.0-beta0006``

fails with:
```
install-package : An error occurred while retrieving package metadata for 'nservicebus.persistence.sql.msbuild.1.0.0-beta0006' from source 'nuget.org'.
  '$version$' is not a valid version string.
```

### PR DESCRIPTION
**Pull request by xavierdecoster**
Fixes #3482 

Using `strictVersionCheck=true` by default, to block packages from being uploaded to nuget.org if they contain package dependencies with an invalid version range.

### CODE REVIEW

File: src/NuGetGallery/Controllers/PackagesController.cs [hunk 1]
```diff
@@ -1149,7 +1150,8 @@ private ActionResult EditFailed(string id, EditPackageRequest formData, Package
                     package = await _packageService.CreatePackageAsync(nugetPackage, packageStreamMetadata, currentUser, commitChanges: false);
                     Debug.Assert(package.PackageRegistration != null);
                 }
-                catch (EntityException ex)
+                catch(Exception ex) 
+                    when (ex is PackagingException || ex is EntityException)
```
Comment (joelverhagen) [inline src/NuGetGallery/Controllers/PackagesController.cs]: nit new line looks weird here

File: tests/NuGetGallery.Core.Facts/Packaging/ManifestValidatorFacts.cs [hunk 2]
```diff
@@ -514,7 +512,25 @@ public void NoErrorIfFrameworkAssemblyReferenceContainsEmptyTargetFramework()
             Assert.Equal(GetErrors(nuspecStream).Length, 0);
         }
 
-        private string[] GetErrors(Stream nuspecStream)
+        [Theory]
+        [InlineData("$version$")]
+        [InlineData("[15.106.0.preview]")]
```
Comment (skofman1) [inline tests/NuGetGallery.Core.Facts/Packaging/ManifestValidatorFacts.cs]: is
<dependency id=""a.b.c"" version="" />
is legal?

File: src/NuGetGallery/Services/PackageService.cs [hunk 3]
```diff
@@ -69,6 +70,18 @@ public class PackageService : IPackageService
...
+        /// <summary>
+        /// When no exceptions thrown, this method ensures the package metadata is valid.
+        /// </summary>
+        /// <param name="packageArchiveReader">
+        /// The <see cref="PackageArchiveReader"/> instance providing the package metadata.
+        /// </param>
+        /// <exception cref="PackagingException">
+        /// This exception will be thrown if an invalid package dependency version range is detected.
+        /// </exception>
+        /// <exception cref="EntityException">
```
Comment (skofman1) [inline src/NuGetGallery/Services/PackageService.cs]: This "contract" is a bit strange... we throw EntityException for every bad metadata value, but a different exception (PackagingException) for bad dependencies.
I suggest wrapping it here in InvalidPackageException. This way we will have a clear contract with the callers.
Also, noticed there are place where we call EnsureValid, but don't expose the failure message correctly:  
https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Controllers/PackagesController.cs#L234

This is one example why having a single exception type thrown will be better.

File: tests/NuGetGallery.Core.Facts/Packaging/ManifestValidatorFacts.cs (hunk 2 above)
Comment (xavierdecoster) [inline tests/NuGetGallery.Core.Facts/Packaging/ManifestValidatorFacts.cs]: The `NuspecReader.GetDependencyGroups(useStrictVersionCheck: true)` does not throw apparently when the dependency version is `""`. Should it? It currently still does a silent fallback to `VersionRange.All` - aka `(,)`.

If it should throw, that means another fix is due on the `NuGet.Packaging` client lib.

Comment (xavierdecoster) [inline tests/NuGetGallery.Core.Facts/Packaging/ManifestValidatorFacts.cs]: Imho, when using `useStrictVersionCheck: true`, we should treat `null` and `""` as _invalid_ versions, and thus throw.

However, the PR that added the overload for strict version checks explicitly added `null` and `""` in the test data for _valid_ version ranges ([highlight](https://github.com/NuGet/NuGet.Client/pull/1262/files#diff-b6f1877463e746b0dfc956a837f5ad5aR301)). An oversight? Or conscious?

Seems like a question @emgarten and @joelverhagen may want to comment on. The fix in the client lib is pretty trivial, but as you can tell, rather important :)

File: tests/NuGetGallery.Core.Facts/Packaging/ManifestValidatorFacts.cs [hunk 4]
```diff
@@ -249,7 +249,7 @@ public class ManifestValidatorFacts
                   </metadata>
                 </package>";
 
-        private const string NuSpecDependencySetContainsInvalidTargetFramework = @"<?xml version=""1.0""?>
+        private const string NuSpecDependencySetContainsInvalidVersionRange = @"<?xml version=""1.0""?>
```
Comment (scottbommarito) [inline tests/NuGetGallery.Core.Facts/Packaging/ManifestValidatorFacts.cs]: With this change, are we no longer testing invalid target frameworks?

File: tests/NuGetGallery.Core.Facts/Packaging/ManifestValidatorFacts.cs (hunk 2 above)
Comment (scottbommarito) [inline tests/NuGetGallery.Core.Facts/Packaging/ManifestValidatorFacts.cs]: Our docs specifically state that you can leave the version range unspecified, and what will happen. IMO we should keep this behavior the same, or, at the bare minimum, investigate how many packages have this issue before changing it.

https://docs.microsoft.com/en-us/nuget/create-packages/dependency-versions#version-ranges

File: src/NuGetGallery.Core/Packaging/PackageMetadata.cs [hunk 5]
```diff
@@ -144,11 +144,19 @@ private Uri GetValue(string key, Uri alternateValue)
...
+        /// <exception cref="PackagingException">
+        /// We default to use a strict version-check on dependency groups. 
+        /// When an invalid dependency version range is detected, a <see cref="PackagingException"/> will be thrown.
+        /// </exception>
         public static PackageMetadata FromNuspecReader(NuspecReader nuspecReader)
         {
             return new PackageMetadata(
                 nuspecReader.GetMetadata().ToDictionary(kvp => kvp.Key, kvp => kvp.Value),
-                nuspecReader.GetDependencyGroups(),
+                nuspecReader.GetDependencyGroups(useStrictVersionCheck: true),
```
Comment (scottbommarito) [inline src/NuGetGallery.Core/Packaging/PackageMetadata.cs]: Not in the scope of this PR, but do we potentially have similar issues with our framework reference groups, packages types, or min client version?

File: tests/NuGetGallery.Core.Facts/Packaging/ManifestValidatorFacts.cs (hunk 4 above)
Comment (xavierdecoster) [inline tests/NuGetGallery.Core.Facts/Packaging/ManifestValidatorFacts.cs]: That string was not used anywhere, I merely put it to use in a different scenario :)

File: tests/NuGetGallery.Core.Facts/Packaging/ManifestValidatorFacts.cs (hunk 2 above)
Comment (xavierdecoster) [inline tests/NuGetGallery.Core.Facts/Packaging/ManifestValidatorFacts.cs]: I spoke to @emgarten and @joelverhagen before implementing this change, and the conclusion was that, moving forward, we should be strict and block this from happening. The documented behavior was more a hack to support floating versions if I understood correctly. The change to reject empty dependency version ranges is also inline with the recommendation as per the docs.

> If no version is specified for a dependency, NuGet behaves as follows:
> 
> * NuGet v2.7.2 and earlier: The latest package version will be used
> * NuGet v2.8 and later: The lowest package version will be used

I think we should add:
> * NuGet v2.8 to v4.1.0: The lowest package version will be used
> * NuGet v4.3.0 and above: no longer supported and considered an invalid dependency version range

**Comment by xavierdecoster** [comment]
Updated this PR to consume the fresh builds that include the `null` and `empty` check fixes. Had to modify a few tests that assumed the empty string fallback to `VersionRange.All`, which we now not only do not recommend, but explicitly block from being pushed/uploaded to the gallery.

Final pair of eyes please? :) @joelverhagen @scottbommarito @skofman1
