### PR TITLE
Fix #2514 - Use optimistic concurrency to prevent multiple UpdateIsLatest calls on same package

### LINKED ISSUE #2514: IsLatest set to multiple versions for some packages
We had a customer reporting issue around viewing profile page : https://github.com/NuGet/NuGetGallery/issues/2494

On debugging, it turned out to be an issue with IsLatest being set on multiple versions on one of packages owned by the user and hence exception is thrown by "FindPackagesByOwner" in packageservice. We need fix the existing data and also see how we end up in that state.

### PR DESCRIPTION
**Pull request by chenriksson**
Approach is same as discussed, but implementation is more complex due to our need to restrict the optimistic concurrency check to CUD operations only on specific columns - which EF doesn't support.

### CODE REVIEW

File: src/NuGetGallery/Services/PackageService.cs [hunk 1]
```diff
@@ -253,7 +266,8 @@ where VersionRange.Parse(d.VersionSpec).Satisfies(packageVersion)
 
             await PublishPackageAsync(package, commitChanges);
         }
-
+        
+        // caller is responsible for calling UpdateIsLatestAsync in separate transaction
```
Comment (joelverhagen) [inline src/NuGetGallery/Services/PackageService.cs]: This should be xmldoc so callers actually see it. Put it on the interface.

File: src/NuGetGallery/Services/PackageService.cs [hunk 2]
```diff
@@ -678,28 +685,149 @@ private void ValidatePackageTitle(PackageMetadata packageMetadata)
...
+            if ((retryCount == 0) && (clears != null))
+            {
+                MergeUpdateIsLatestClearsWithSets(clears, sets);
+            }
+
+            // performed updates on separate context in order to refresh entities between retries
+            var altEntitiesContext = CreateNewEntitiesContext();
+
+            // suspend retry execution strategy which does not support user initiated transactions
+            EntitiesConfiguration.SuspendExecutionStrategy = true;
```
Comment (joelverhagen) [inline src/NuGetGallery/Services/PackageService.cs]: What is `altEntitiesContext.GetDatabase();` throws? Won't this static stay `true`? In these cases, I like making an `IDisposable` which toggles the static on and off.

Another concern -- won't this effect other threads?

File: src/NuGetGallery/Services/PackageService.cs [hunk 3]
```diff
@@ -678,28 +685,149 @@ private void ValidatePackageTitle(PackageMetadata packageMetadata)
...
+                {
+                    foreach (var set in sets)
+                    {
+                        if (await UpdateIsLatestInDatabaseWithConcurrencyCheckAsync(altDatabase, set) != 1)
+                        {
+                            transaction.Rollback();
+
+                            var packageRegistration = sets.First().Package.PackageRegistration;
+
+                            if (retryCount++ < UpdateIsLatestMaxRetries)
```
Comment (joelverhagen) [inline src/NuGetGallery/Services/PackageService.cs]: Please increment on a separate line. This is less readable.

File: src/NuGetGallery/Services/PackageService.cs [hunk 4]
```diff
@@ -678,28 +685,149 @@ private void ValidatePackageTitle(PackageMetadata packageMetadata)
...
+                            {
+                                await Task.Delay(retryCount * 500);
+                                await UpdateIsLatestAsync(packageRegistration, retryCount);
+                            }
+                            else
+                            {
+                                _trace.Error(String.Format("UpdateIsLatestAsync retry exceeded for package '{0}'", packageRegistration.Id));
```
Comment (joelverhagen) [inline src/NuGetGallery/Services/PackageService.cs]: This case is really bad, right? What will the playbook be if we encounter one of these exceptions?

**Comment by joelverhagen** [comment]
I'm interested in what a functional test on this change would look like. Before the change, could we have written a test to consistently reproduce the issue (by mocking out as much as possible and throwing enough threads at it)?

File: src/NuGetGallery/Controllers/ApiController.cs [hunk 5]
```diff
@@ -393,6 +393,9 @@ public virtual Task<ActionResult> CreatePackagePost()
                             throw;
                         }
 
+                        // handle in separate transaction because of concurrency check with retry
```
Comment (skofman1) [inline src/NuGetGallery/Controllers/ApiController.cs]: nit: capital letter in the beginning of the comment to match the rest of the file

File: src/NuGetGallery/Services/PackageService.cs [hunk 6]
```diff
@@ -678,28 +685,149 @@ private void ValidatePackageTitle(PackageMetadata packageMetadata)
...
+                    match.OriginalIsLatestStable = clear.OriginalIsLatestStable;
+                }
+            }
+            
+            sets.RemoveAll(pe => !pe.StateChanged());
+        }
+
+        protected internal virtual IEntitiesContext CreateNewEntitiesContext()
+        {
+            var connectionString = _entitiesContext.GetDatabase().Connection.ConnectionString;
```
Comment (skofman1) [inline src/NuGetGallery/Services/PackageService.cs]: we use the connection string from web.config: https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery.Core/Entities/EntitiesContext.cs#L25

return new EntitiesContext() should do the trick

File: src/NuGetGallery/Services/PackageService.cs [hunk 7]
```diff
@@ -678,28 +685,149 @@ private void ValidatePackageTitle(PackageMetadata packageMetadata)
...
+            // update entity in memory first
+            var packageClears = new List<UpdateIsLatestPackageEdit>();
+            var packageSets = new List<UpdateIsLatestPackageEdit>();
+            
             foreach (var pv in packageRegistration.Packages.Where(p => p.IsLatest || p.IsLatestStable))
             {
-                pv.IsLatest = false;
-                pv.IsLatestStable = false;
-                pv.LastUpdated = DateTime.UtcNow;
+                packageClears.Add(UpdateIsLatestPackageEdit.Set(pv, false, false));
```
Comment (skofman1) [inline src/NuGetGallery/Services/PackageService.cs]: please use named parameters, for readability

**Comment by skofman1** [comment]
>                     // a release version and set it to IsLatest.

isLatestStable.


---
Refers to: src/NuGetGallery/Services/PackageService.cs:835 in 7f861cd. [](commit_id = 7f861cd68dfdcc33b9e5f9f66f3feda61c41b8c9, deletion_comment = False)

File: src/NuGetGallery/Services/PackageService.cs (hunk 4 above)
Comment (chenriksson) [inline src/NuGetGallery/Services/PackageService.cs]: We'd hit this block if the request detected 3 concurrency conflicts in a row, in which case it would not update the flags.

This is unlikely to be a problem, since the real package CUD was already committed in a separate request. More than likely a concurrent request has already updated isLatest/isLatestStable, and the retry would detect that no changes are necessary.

This trace would at least give us monitoring if there are multiple concurrency conflicts in a row. Playbook would be to just check the package to see if the latest is set correctly... but more than likely it corrected itself.

File: src/NuGetGallery/Services/PackageService.cs (hunk 2 above)
Comment (chenriksson) [inline src/NuGetGallery/Services/PackageService.cs]: Shouldn't affect other threads. SuspendExecutionStrategy uses [CallContext](https://msdn.microsoft.com/en-us/library/system.runtime.remoting.messaging.callcontext(v=vs.110).aspx) which is similar to thread local storage. Note that this is also used in [PackageDeleteService](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Services/PackageDeleteService.cs#L59), which also uses custom transactions.

I wasn't thinking about GetDatabase throwing, but perhaps it could if the connection was somehow closed. I'll just expand the scope of the try/finally, which I think will be less work than introducing a disposable.

File: src/NuGetGallery/Services/PackageService.cs [hunk 8]
```diff
@@ -678,28 +685,149 @@ private void ValidatePackageTitle(PackageMetadata packageMetadata)
...
+            var connectionString = _entitiesContext.GetDatabase().Connection.ConnectionString;
+            return new EntitiesContext(connectionString, false);
+        }
+
+        private async Task UpdateIsLatestInDatabaseAsync(List<UpdateIsLatestPackageEdit> clears, List<UpdateIsLatestPackageEdit> sets, int retryCount = 0)
+        {
+            if ((retryCount == 0) && (clears != null))
+            {
+                MergeUpdateIsLatestClearsWithSets(clears, sets);
+            }
```
Comment (chenriksson) [inline src/NuGetGallery/Services/PackageService.cs]: Need to remove conditional around MergeUpdateIsLatestClearsWithSets. Originally I had bug where retry was calling back into UpdateIsLatestInDatabaseAsync without refresh and recalculating the latest.

File: src/NuGetGallery/Services/PackageService.cs [hunk 9]
```diff
@@ -779,5 +898,40 @@ private void NotifyIndexingService()
                 }
             }
         }
+
+        private class UpdateIsLatestPackageEdit
```
Comment (cristinamanum) [inline src/NuGetGallery/Services/PackageService.cs]: It would be great to add few comments about this class.

File: src/NuGetGallery/Services/PackageService.cs [hunk 10]
```diff
@@ -678,28 +680,153 @@ private void ValidatePackageTitle(PackageMetadata packageMetadata)
...
         }
 
-        public async Task UpdateIsLatestAsync(PackageRegistration packageRegistration, bool commitChanges = true)
+        protected internal virtual Task<int> ExecuteSqlCommandAsync(Database database, string sql, params object[] parameters)
         {
-            if (!packageRegistration.Packages.Any())
+            return database.ExecuteSqlCommandAsync(sql, parameters);
+        }
+
+        private async Task<int> UpdateIsLatestInDatabaseWithConcurrencyCheckAsync(Database database, UpdateIsLatestPackageEdit packageEdit)
```
Comment (cristinamanum) [inline src/NuGetGallery/Services/PackageService.cs]: nit: line too long.

File: src/NuGetGallery/Services/PackageService.cs [hunk 11]
```diff
@@ -678,28 +680,153 @@ private void ValidatePackageTitle(PackageMetadata packageMetadata)
...
+        {
+            return await ExecuteSqlCommandAsync(database, @"
+            UPDATE [dbo].[Packages]
+            SET [IsLatest] = {1}, [IsLatestStable] = {2}, [LastUpdated] = GETUTCDATE()
+            WHERE( ([Key] = {0}) AND ([IsLatest] = {3}) AND ([IsLatestStable] = {4}) )
+            SELECT @@ROWCOUNT",
+            packageEdit.Package.Key, packageEdit.Package.IsLatest, packageEdit.Package.IsLatestStable, packageEdit.OriginalIsLatest, packageEdit.OriginalIsLatestStable);
+        }
+
+        private static bool PackagesMatch(Package first, Package second)
```
Comment (cristinamanum) [inline src/NuGetGallery/Services/PackageService.cs]: Maybe PackagesVersionMatch instead of the PackagesMatch?

File: src/NuGetGallery/Services/PackageService.cs [hunk 12]
```diff
@@ -678,28 +680,153 @@ private void ValidatePackageTitle(PackageMetadata packageMetadata)
...
+            {
+                return false;
+            }
+            else
+            {
+                return first.Version.Equals(second.Version, StringComparison.OrdinalIgnoreCase);
+            }
+        }
+
+        private static void MergeUpdateIsLatestClearsWithSets(List<UpdateIsLatestPackageEdit> clears, List<UpdateIsLatestPackageEdit> sets)
```
Comment (cristinamanum) [inline src/NuGetGallery/Services/PackageService.cs]: It would be great to have few comments. Also the line length  seems to be large.

File: src/NuGetGallery/Services/PackageService.cs [hunk 13]
```diff
@@ -678,28 +685,149 @@ private void ValidatePackageTitle(PackageMetadata packageMetadata)
             }
         }
 
-        public async Task UpdateIsLatestAsync(PackageRegistration packageRegistration, bool commitChanges = true)
+        protected internal virtual Task<int> ExecuteSqlCommandAsync(Database database, string sql, params object[] parameters)
+        {
+            return database.ExecuteSqlCommandAsync(sql, parameters);
+        }
+
+        private async Task<int> UpdateIsLatestInDatabaseWithConcurrencyCheckAsync(Database database, UpdateIsLatestPackageEdit packageEdit)
```
Comment (skofman1) [inline src/NuGetGallery/Services/PackageService.cs]: >int [](start = 27, length = 3)

returning true/false will make the code more readable.

File: src/NuGetGallery/Services/PackageService.cs [hunk 14]
```diff
@@ -678,28 +685,149 @@ private void ValidatePackageTitle(PackageMetadata packageMetadata)
...
+                    {
+                        if (await UpdateIsLatestInDatabaseWithConcurrencyCheckAsync(altDatabase, set) != 1)
+                        {
+                            transaction.Rollback();
+
+                            var packageRegistration = sets.First().Package.PackageRegistration;
+
+                            if (retryCount++ < UpdateIsLatestMaxRetries)
+                            {
+                                await Task.Delay(retryCount * 500);
```
Comment (skofman1) [inline src/NuGetGallery/Services/PackageService.cs]: >500 [](start = 62, length = 3)

const

File: src/NuGetGallery/Services/PackageService.cs [hunk 15]
```diff
@@ -678,28 +685,149 @@ private void ValidatePackageTitle(PackageMetadata packageMetadata)
...
+                                await UpdateIsLatestAsync(packageRegistration, retryCount);
```
Comment (skofman1) [inline src/NuGetGallery/Services/PackageService.cs]: >UpdateIsLatestAsync [](start = 38, length = 19)

this code could be simpler if the retries were done in UpdateIsLatestAsync. In this case UpdateIsLatestInDatabaseAsync calls the method that called it (UpdateIsLatestAsync), that calls it again, creating a recursion..
If UpdateIsLatestInDatabaseAsync returned a failure, UpdateIsLatestAsync can call it again until retries are exhausted.

**Comment by skofman1** [comment]
>             public async Task WillUpdateIsLatest1()

This naming is extremely confusing. Could you rename those?

---
Refers to: tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs:1074 in 7f861cd. [](commit_id = 7f861cd68dfdcc33b9e5f9f66f3feda61c41b8c9, deletion_comment = False)

**Comment by skofman1** [comment]
Regarding functional tests: Scott wrote a test that pushes a bunch of packages and verified timestamps: https://github.com/NuGet/NuGetGallery/blob/ce6c5d603e76ca1265c0b759d4e0d898acd7349d/tests/NuGetGallery.FunctionalTests/ODataFeeds/V2FeedExtendedTests.cs#L64

You could do something similar

File: src/NuGetGallery/Services/PackageService.cs [hunk 16]
```diff
@@ -678,28 +680,153 @@ private void ValidatePackageTitle(PackageMetadata packageMetadata)
...
+        private async Task UpdateIsLatestInDatabaseAsync(List<UpdateIsLatestPackageEdit> clears, List<UpdateIsLatestPackageEdit> sets, int retryCount = 0)
+        {
+            MergeUpdateIsLatestClearsWithSets(clears, sets);
+            if (sets.Count == 0)
             {
                 return;
             }
 
-            // TODO: improve setting the latest bit; this is horrible. Trigger maybe?
+            // performed updates on separate context in order to refresh entities between retries
```
Comment (scottbommarito) [inline src/NuGetGallery/Services/PackageService.cs]: Capitalize please.

File: src/NuGetGallery/Services/PackageService.cs [hunk 17]
```diff
@@ -678,28 +680,153 @@ private void ValidatePackageTitle(PackageMetadata packageMetadata)
...
+                        transaction.Rollback();
+                        _trace.Error(ex.ToString());
+                    }
+                }
+            }
+            finally
+            {
+                EntitiesConfiguration.SuspendExecutionStrategy = false;
+
+                var disposableContext = altEntitiesContext as IDisposable;
```
Comment (scottbommarito) [inline src/NuGetGallery/Services/PackageService.cs]: Could we move the declaration of `altEntitiesContext` inside the `try-finally` and then use a `using` statement instead of having this in the `finally` statement?

File: src/NuGetGallery/Services/PackageService.cs [hunk 18]
```diff
@@ -678,28 +680,153 @@ private void ValidatePackageTitle(PackageMetadata packageMetadata)
...
+            }
+        }
+
+        public Task UpdateIsLatestAsync(PackageRegistration packageRegistration)
+        {
+            return UpdateIsLatestAsync(packageRegistration, retryCount: 0);
+        }
+
+        private Task UpdateIsLatestAsync(PackageRegistration packageRegistration, int retryCount)
+        {
```
Comment (cristinamanum) [inline src/NuGetGallery/Services/PackageService.cs]: Is the retryCount used in this method?

File: tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs [hunk 19]
```diff
@@ -1013,41 +1052,22 @@ public class TheCreatePackageOwnerRequestMethod
...
-
-                // Act
-                await service.UpdateIsLatestAsync(packageRegistration, commitChanges: false);
-
-                // Assert
-                packageRepository.Verify(r => r.CommitChangesAsync(), Times.Never());
-            }
-
-            [Fact]
             public async Task CommitIfCommitChangesIsTrue()
```
Comment (scottbommarito) [inline tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs]: I suggest renaming this to `AlwaysCommitsChanges` because the commit changes option was removed from the function.

File: tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs [hunk 20]
```diff
@@ -1105,7 +1122,42 @@ public class TheUpdateIsLatestMethod
                 Assert.False(package10A.IsLatestStable);
                 Assert.False(package09.IsLatest);
                 Assert.False(package09.IsLatestStable);
-                packageRepository.Verify();
+
+                service.Verify(s => s.ExecuteSqlCommandAsync(It.IsAny<Database>(), It.IsAny<string>(), It.IsAny<object[]>()), Times.Once);
+            }
+
+            [Fact]
+            public async Task WillUpdateIsLatest3()
```
Comment (scottbommarito) [inline tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs]: We should add some unit tests that assume test the behavior when transactions fail, and enumerating different possible scenarios. You can do this by mocking the `UpdateIsLatestInDatabaseWithConcurrencyCheckAsync` method and performing different behaviors based on the `UpdateIsLatestPackageEdit` object supplied.

File: src/NuGetGallery/Services/PackageService.cs (hunk 18 above)
Comment (chenriksson) [inline src/NuGetGallery/Services/PackageService.cs]: Yes, on retry of concurrency conflict in UpdateIsLatestInDatabaseAsync

File: src/NuGetGallery/Services/PackageService.cs [hunk 21]
```diff
@@ -678,52 +680,171 @@ private void ValidatePackageTitle(PackageMetadata packageMetadata)
...
             }
 
-            // TODO: improve setting the latest bit; this is horrible. Trigger maybe?
+            // performed updates on separate context in order to refresh entities between retries
+            var altEntitiesContext = CreateNewEntitiesContext();
+
+            try
+            {
+                // suspend retry execution strategy which does not support user initiated transactions
+                EntitiesConfiguration.SuspendExecutionStrategy = true;
```
Comment (dtivel) [inline src/NuGetGallery/Services/PackageService.cs]: I'd rather see an `IDisposable` pattern here.  I realize other places that set this property don't use a `try...finally` block, so bonus points for fixing those.

```
public class EntitiesConfiguration
    : DbConfiguration
{
    public EntitiesConfiguration()
    {
        // Configure Connection Resiliency / Retry Logic
        // See https://msdn.microsoft.com/en-us/data/dn456835.aspx and msdn.microsoft.com/en-us/data/dn307226
        SetExecutionStrategy("System.Data.SqlClient", () => UseRetriableExecutionStrategy
            ? new SqlAzureExecutionStrategy() : (IDbExecutionStrategy)new DefaultExecutionStrategy());
    }

    private static bool UseRetriableExecutionStrategy
    {
        get
        {
            return (bool?)CallContext.LogicalGetData(nameof(UseRetriableExecutionStrategy)) ?? true;
        }
        set
        {
            CallContext.LogicalSetData(nameof(UseRetriableExecutionStrategy), value);
        }
    }

    internal IDisposable SuspendRetriableExecutionStrategy()
    {
        return new ExecutionStrategySuspension();
    }

    private class ExecutionStrategySuspension : IDisposable
    {
        private readonly bool _originalValue;

        internal ExecutionStrategySuspension()
        {
            _originalValue = UseRetriableExecutionStrategy;

            UseRetriableExecutionStrategy = false;
        }

        public void Dispose()
        {
            UseRetriableExecutionStrategy = _originalValue;
        }
    }
}
```

Call sites:

```
using (var retrySuspension = EntitiesConfiguration.SuspendRetriableExecutionStrategy())
{
    ...
}
```

Then you can remove comments like this:

    // suspend retry execution strategy which does not support user initiated transactions

File: src/NuGetGallery/Services/PackageService.cs [hunk 22]
```diff
@@ -678,52 +680,171 @@ private void ValidatePackageTitle(PackageMetadata packageMetadata)
...
-            if (!packageRegistration.Packages.Any())
+            return database.ExecuteSqlCommandAsync(sql, parameters);
+        }
+
+        private async Task<int> UpdateIsLatestInDatabaseWithConcurrencyCheckAsync(Database database, UpdateIsLatestPackageEdit packageEdit)
+        {
+            return await ExecuteSqlCommandAsync(database, @"
+                UPDATE [dbo].[Packages]
+                SET [IsLatest] = {1}, [IsLatestStable] = {2}, [LastUpdated] = GETUTCDATE()
+                WHERE( ([Key] = {0}) AND ([IsLatest] = {3}) AND ([IsLatestStable] = {4}) )
```
Comment (dtivel) [inline src/NuGetGallery/Services/PackageService.cs]: Can you remove the superfluous parentheses?

    WHERE [Key] = {0} AND [IsLatest] = {3} AND [IsLatestStable] = {4}

Also, the out-of-order arguments seems a little error-prone.

File: src/NuGetGallery/Services/PackageService.cs (hunk 17 above)
Comment (dtivel) [inline src/NuGetGallery/Services/PackageService.cs]: Yes, and you don't need to cast.  `DbContext` implements `IDisposable`.

File: src/NuGetGallery/Services/PackageService.cs [hunk 23]
```diff
@@ -779,5 +900,43 @@ private void NotifyIndexingService()
...
+                return new UpdateIsLatestPackageEdit(package, isLatest, isLatestStable);
+            }
+
+            public Package Package { get; private set; }
+
+            public bool OriginalIsLatest { get; set; }
+
+            public bool OriginalIsLatestStable { get; set; }
+
+            public bool StateChanged()
```
Comment (dtivel) [inline src/NuGetGallery/Services/PackageService.cs]: `HasStateChanged()` or simply `HasChanged()`.

File: src/NuGetGallery/Services/PackageService.cs [hunk 24]
```diff
@@ -678,52 +680,171 @@ private void ValidatePackageTitle(PackageMetadata packageMetadata)
...
+                EntitiesConfiguration.SuspendExecutionStrategy = true;
+
+                var altDatabase = altEntitiesContext.GetDatabase();
+                using (var transaction = altDatabase.BeginTransaction(IsolationLevel.ReadCommitted))
+                {
+                    try
+                    {
+                        foreach (var set in sets)
+                        {
+                            if (await UpdateIsLatestInDatabaseWithConcurrencyCheckAsync(altDatabase, set) != 1)
```
Comment (dtivel) [inline src/NuGetGallery/Services/PackageService.cs]: Is it worth building a single SQL statement to make one DB call?

```
declare @rowcount int = 0

update [dbo].[Packages]
    ...

set @rowcount = @rowcount + @@rowcount

update [dbo].[Packages]
    ...

set @rowcount = @rowcount + @@rowcount

select @rowcount
```

File: src/NuGetGallery/Services/PackageService.cs [hunk 25]
```diff
@@ -678,52 +680,171 @@ private void ValidatePackageTitle(PackageMetadata packageMetadata)
...
+                            {
+                                transaction.Rollback();
+
+                                var packageRegistration = sets.First().Package.PackageRegistration;
+
+                                if (retryCount < UpdateIsLatestMaxRetries)
+                                {
+                                    retryCount++;
+                                    await Task.Delay(retryCount * 500);
+                                    await UpdateIsLatestAsync(packageRegistration, retryCount);
```
Comment (dtivel) [inline src/NuGetGallery/Services/PackageService.cs]: Can you eliminate the recursion?

File: src/NuGetGallery/Services/PackageService.cs (hunk 17 above)
Comment (chenriksson) [inline src/NuGetGallery/Services/PackageService.cs]: This was to support the Mock<IEntitiesContext> object used by tests, which wasn't IDisposable. Will see if there's another way.

File: src/NuGetGallery/Services/IPackageService.cs [hunk 26]
```diff
@@ -16,13 +16,25 @@ public interface IPackageService
         IEnumerable<PackageRegistration> FindPackageRegistrationsByOwner(User user);
         IEnumerable<Package> FindDependentPackages(Package package);
 
-        Task UpdateIsLatestAsync(PackageRegistration packageRegistration, bool commitChanges = true);
+        /// <summary>
+        /// Updates IsLatest/IsLatestStable flags after a package CUD operation.
```
Comment (chenriksson) [inline src/NuGetGallery/Services/IPackageService.cs]: Will remove the abbr. CRUD=create/retrieve/update/delete, so CUD refers to the write operations.

File: src/NuGetGallery/Controllers/ApiController.cs [hunk 27]
```diff
@@ -503,6 +513,10 @@ private static ActionResult BadRequestForExceptionMessage(Exception ex)
             }
 
             await PackageService.MarkPackageListedAsync(package);
+            
+            // handle in separate transaction because of concurrency check with retry
+            await PackageService.UpdateIsLatestAsync(package.PackageRegistration);
```
Comment (chenriksson) [inline src/NuGetGallery/Controllers/ApiController.cs]: Don't think I can, because MarkPackageUnlistedAsync can be called without commit. For instance, from PackagesController::VerifyPackage. UpdateIsLatestAsync needs to be called last after any other package updates have been committed.

File: src/NuGetGallery/Controllers/ApiController.cs [hunk 28]
```diff
@@ -470,6 +473,13 @@ private static ActionResult BadRequestForExceptionMessage(Exception ex)
             }
 
             await PackageService.MarkPackageUnlistedAsync(package);
+            
+            // handle in separate transaction because of concurrency check with retry
+            if (package.IsLatest || package.IsLatestStable)
```
Comment (chenriksson) [inline src/NuGetGallery/Controllers/ApiController.cs]: See comment for MarkPackageUnlistedAsync. While this method also supports not committing changes, only test code does it. So, I could remove that option and move UpdateIsLatestAsync back inside, but I'm inclined to keep these methods consistent. Let me know if you disagree.

File: src/NuGetGallery/Services/PackageService.cs [hunk 29]
```diff
@@ -779,5 +898,40 @@ private void NotifyIndexingService()
...
+            }
+
+            public static UpdateIsLatestPackageEdit Set(Package package, bool isLatest, bool isLatestStable)
+            {
+                return new UpdateIsLatestPackageEdit(package, isLatest, isLatestStable);
+            }
+
+            public Package Package { get; private set; }
+
+            public bool OriginalIsLatest { get; set; }
```
Comment (chenriksson) [inline src/NuGetGallery/Services/PackageService.cs]: These may change in MergeUpdateIsLatestClearsWithSets

File: src/NuGetGallery/Services/PackageService.cs [hunk 30]
```diff
@@ -678,28 +680,153 @@ private void ValidatePackageTitle(PackageMetadata packageMetadata)
...
+        public Task UpdateIsLatestAsync(PackageRegistration packageRegistration)
+        {
+            return UpdateIsLatestAsync(packageRegistration, retryCount: 0);
+        }
+
+        private Task UpdateIsLatestAsync(PackageRegistration packageRegistration, int retryCount)
+        {
+            if (!packageRegistration.Packages.Any())
+            {
+                return Task.FromResult(0);
```
Comment (chenriksson) [inline src/NuGetGallery/Services/PackageService.cs]: Don't think I can. Gallery's TargetFramework is 4.5.2, but this was added in 4.6.

File: src/NuGetGallery/Services/PackageService.cs (hunk 21 above)
Comment (chenriksson) [inline src/NuGetGallery/Services/PackageService.cs]: ok, that does look nice. :-)

File: src/NuGetGallery/Services/PackageService.cs [hunk 31]
```diff
@@ -678,28 +680,153 @@ private void ValidatePackageTitle(PackageMetadata packageMetadata)
...
+            }
+
+            // update entity in memory first
+            var packageClears = new List<UpdateIsLatestPackageEdit>();
```
Comment (chenriksson) [inline src/NuGetGallery/Services/PackageService.cs]: @scottbommarito Cleaned up to remove merge (and UpdateIsLatestPackageEdit class) altogether, opting instead to utilize the EF change tracker. Only downside is EF change tracker isn't available for unit tests.

**Comment by chenriksson** [comment]
@skofman1 @joelverhagen still working on functional test for this, so will have another push coming

File: src/NuGetGallery/Services/PackageService.cs [hunk 32]
```diff
@@ -678,51 +680,128 @@ private void ValidatePackageTitle(PackageMetadata packageMetadata)
...
-                        latestReleasePackage.LastUpdated = DateTime.UtcNow;
-                    }
+                    transaction.Commit();
+                    return true;
                 }
                 else
                 {
-                    // Only release versions are marked as IsLatestStable.
-                    latestPackage.IsLatestStable = true;
+                    transaction.Rollback();
```
Comment (scottbommarito) [inline src/NuGetGallery/Services/PackageService.cs]: I would add a comment to this block explaining why we're rolling back.

```
// Some of the packages have been modified by another transaction before we could commit our changes.
```

File: src/NuGetGallery/Services/IPackageService.cs [hunk 33]
```diff
@@ -16,13 +16,37 @@ public interface IPackageService
         IEnumerable<PackageRegistration> FindPackageRegistrationsByOwner(User user);
         IEnumerable<Package> FindDependentPackages(Package package);
 
-        Task UpdateIsLatestAsync(PackageRegistration packageRegistration, bool commitChanges = true);
+        /// <summary>
+        /// Updates IsLatest/IsLatestStable flags after a package create, update or delete operation.
+        /// 
+        /// Optimistic concurrency was added to this update to prevent multiple threads (in the same
```
Comment (scottbommarito) [inline src/NuGetGallery/Services/IPackageService.cs]: This is a very well-written and clear comment; however, I'm worried that putting it here may not be the best place for it. It's mostly an explanation of the implementation, and it doesn't really belong on the interface. I would suggest spreading this out over the relevant parts of the implementation, so that the commentary is directly integrated with the experience of reading the code. For example, you could move the comment about how `UpdateIsLatest` uses its own EF context to the part of the code where you actually create a separate context.

File: src/NuGetGallery/Services/PackageDeleteService.cs [hunk 34]
```diff
@@ -56,107 +56,112 @@ public class PackageDeleteService
...
-                // Increase command timeout
-                _entitiesContext.SetCommandTimeout(seconds: 300);
+            List<PackageRegistration> packageRegistrations;
 
-                // Keep package registrations
-                var packageRegistrations = packages
-                    .GroupBy(p => p.PackageRegistration)
-                    .Select(g => g.First().PackageRegistration)
-                    .ToList();
+            using (var retrySuspension = EntitiesConfiguration.SuspendRetriableExecutionStrategy())
```
Comment (scottbommarito) [inline src/NuGetGallery/Services/PackageDeleteService.cs]: Given that you don't use `retrySuspension` in your code at all, is it necessary to declare it or can you just do 
```using (EntitiesConfiguration.SuspendRetriableExecutionStrategy())```?

File: src/NuGetGallery.Core/Entities/EntitiesConfiguration.cs [hunk 35]
```diff
@@ -15,19 +16,41 @@ public EntitiesConfiguration()
...
+                CallContext.LogicalSetData("UseRetriableExecutionStrategy", value);
+            }
+        }
+
+        public static IDisposable SuspendRetriableExecutionStrategy()
+        {
+            return new ExecutionStrategySuspension();
+        }
+
+        private class ExecutionStrategySuspension : IDisposable
```
Comment (skofman1) [inline src/NuGetGallery.Core/Entities/EntitiesConfiguration.cs]: RetriableExecutionStrategySuspension

**Comment by skofman1** [comment]
Looks great! :shipit:

File: tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs [hunk 36]
```diff
@@ -581,6 +581,8 @@ public class TheEditMethod
                     .Throws(new Exception("Shouldn't be called"));
                 packageService.Setup(svc => svc.FindPackageByIdAndVersion("Foo", "1.0", true))
                     .Returns(package).Verifiable();
+                packageService.Setup(svc => svc.UpdateIsLatestAsync(It.IsAny<PackageRegistration>()))
+                    .Returns(Task.FromResult(0)).Verifiable();
```
Comment (dtivel) [inline tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs]: Does `Task.CompletedTask` also work?  I think it's more clear than `Task.FromResult(0)`.

File: tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs [hunk 37]
```diff
@@ -1607,6 +1609,8 @@ public class TheVerifyPackageActionForPostRequests
                         .Returns(Task.CompletedTask);
                     fakePackageService.Setup(x => x.MarkPackageUnlistedAsync(fakePackage, false))
                         .Returns(Task.CompletedTask);
+                    fakePackageService.Setup(x => x.UpdateIsLatestAsync(It.IsAny<PackageRegistration>()))
+                        .Returns(Task.FromResult(0));
```
Comment (dtivel) [inline tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs]: `Task.CompletedTask`?

File: tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs [hunk 38]
```diff
@@ -1105,7 +1109,42 @@ public class TheUpdateIsLatestMethod
                 Assert.False(package10A.IsLatestStable);
                 Assert.False(package09.IsLatest);
                 Assert.False(package09.IsLatestStable);
-                packageRepository.Verify();
+
+                service.Verify(s => s.TryUpdateIsLatestInDatabase(It.IsAny<IEntitiesContext>()), Times.Once);
+            }
+
+            [Fact]
+            public async Task UpdateIsLatestAsync_SameLatestAndLatestStableVersionsWithClear()
```
Comment (dtivel) [inline tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs]: `SameNewLatestAndLatestStableVersions` sounds more clear than `SameLatestAndLatestStableVersionsWithClear`.

**Comment by chenriksson** [comment]
@scottbommarito look ok to you?

File: tests/NuGetGallery.FunctionalTests.Core/Helpers/ODataHelper.cs [hunk 39]
```diff
@@ -59,33 +61,49 @@ public ODataHelper(ITestOutputHelper testOutputHelper)
...
+        {
+            WriteLine($"Getting properties for package '{packageId}' with version '{version}'.");
+
+            var packageResponse = await GetPackageDataInResponse(url, packageId, version);
+            if (!string.IsNullOrEmpty(packageResponse))
             {
-                WriteLine($"Package data does not contain '{propertyName}' timestamp!");
-                return null;
-            }
+                var propertiesStart = Math.Max(packageResponse.IndexOf("<m:properties>"), 0);
```
Comment (dtivel) [inline tests/NuGetGallery.FunctionalTests.Core/Helpers/ODataHelper.cs]: Why not just use `XmlDocument` or `XDocument` to read the XML?

File: tests/NuGetGallery.FunctionalTests.Core/Helpers/ODataHelper.cs [hunk 40]
```diff
@@ -59,33 +61,49 @@ public ODataHelper(ITestOutputHelper testOutputHelper)
...
+                var propertiesEnd = packageResponse.IndexOf("</m:properties>", propertiesStart);
+                if (propertiesEnd > 0)
+                {
+                    propertiesStart += 14;
+                    var propertiesContent = packageResponse.Substring(propertiesStart, propertiesEnd - propertiesStart);
+                    var properties = new Dictionary<string, object>();
 
-            var timestampStartIndex = timestampTagIndex + timestampStartTag.Length;
-            var timestampLength = packageResponse.Substring(timestampStartIndex).IndexOf(timestampEndTag);
+                    var propertyRegEx = new Regex(GetPackagePropertyRegexPattern);
```
Comment (blowdart) [inline tests/NuGetGallery.FunctionalTests.Core/Helpers/ODataHelper.cs]: Ensure there's a timeout on all regexs

File: tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs [hunk 41]
```diff
@@ -51,9 +50,9 @@ public class PackagesControllerFacts
             if (uploadFileService == null)
             {
                 uploadFileService = new Mock<IUploadFileService>();
-                uploadFileService.Setup(x => x.DeleteUploadFileAsync(It.IsAny<int>())).Returns(Task.FromResult(0));
+                uploadFileService.Setup(x => x.DeleteUploadFileAsync(It.IsAny<int>())).Returns(Task.CompletedTask);
```
Comment (scottbommarito) [inline tests/NuGetGallery.Facts/Controllers/PackagesControllerFacts.cs]: thanks for doing this...so much cleaner

File: tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs [hunk 42]
```diff
@@ -120,18 +153,24 @@ public class PackageServiceFacts
...
                 packageRepository.Object,
                 packageOwnerRequestRepo.Object,
+                entitiesContext.Object,
+                diagnosticsService.Object,
                 indexingService.Object,
                 packageNamingConflictValidator,
                 auditingService);
 
+            packageService.Setup(s => s.TryUpdateIsLatestInDatabase(It.IsAny<IEntitiesContext>()))
+                .Returns(Task.FromResult(true));
```
Comment (scottbommarito) [inline tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs]: `Task.CompletedTask`?

File: tests/NuGetGallery.FunctionalTests.Core/Helpers/ODataHelper.cs (hunk 39 above)
Comment (scottbommarito) [inline tests/NuGetGallery.FunctionalTests.Core/Helpers/ODataHelper.cs]: Note that using `XmlDocument` or `XDocument` would also remove the potential for the regex to take an extremely long time as @blowdart noted.

File: tests/NuGetGallery.FunctionalTests/ODataFeeds/V2FeedExtendedTests.cs [hunk 43]
```diff
@@ -87,7 +87,56 @@ public V2FeedExtendedTests(ITestOutputHelper testOutputHelper)
...
+            // push all and verify; ~15-20 concurrency conflicts seen in testing
+            var concurrentTasks = new Task[packageVersions.Count];
+            for (int i = 0; i < concurrentTasks.Length; i++)
+            {
+                var packageVersion = packageVersions[i];
+                concurrentTasks[i] = Task.Run(() => _clientSdkHelper.UploadNewPackage(packageId, version: packageVersion));
+            }
+            Task.WaitAll(concurrentTasks);
+            
+            await CheckPackageLatestVersions(packageId, packageVersions, expectedLatest: "7.0.2-abc", expectedLatestStable: "7.0.1");
```
Comment (scottbommarito) [inline tests/NuGetGallery.FunctionalTests/ODataFeeds/V2FeedExtendedTests.cs]: I would prefer that you had these values in a variable instead of copying them here.

```
var latestVersion = "7.0.2-abc"
var latestStable = "7.0.1"

var latestVersionHalf = "3.0.2-abc"
var latestStableHalf = "3.0.1"

var packageVersions = new List<string>()
{
    "1.0.0-a",  "1.0.0-b",  "1.0.0",  "1.0.1",  "1.0.2-abc",
    "2.0.0-a",  "2.0.0-b",  "2.0.0",  "2.0.1",  "2.0.2-abc",
    "3.0.0-a",  "3.0.0-b",  "3.0.0",  latestStableHalf,  latestVersionHalf,
    "4.0.0-a",  "4.0.0-b",  "4.0.0",  "4.0.1",  "4.0.2-abc",
    "6.0.0-a",  "6.0.0-b",  "6.0.0",  "6.0.1",  "6.0.2-abc",
    "7.0.0-a",  "7.0.0-b",  "7.0.0",  latestStable,  latestVersion
};
...
await CheckPackageLatestVersions(packageId, packageVersions, latestVersion, latestStable);
...
// unlist last half and verify; ~1-2 concurrency conflicts seen in testing
for (int i = concurrentTasks.Length - 1; i > concurrentTasks.IndexOf(latestVersionHalf); i--)
...
await CheckPackageLatestVersions(packageId, packageVersions, latestVersionHalf, latestStableHalf);

// unlist remaining and verify; ~1-2 concurrency conflicts seen in testing
for (int i = concurrentTasks.IndexOf(latestVersionHalf); i >= 0; i--)
```

File: tests/NuGetGallery.FunctionalTests/ODataFeeds/V2FeedExtendedTests.cs [hunk 44]
```diff
@@ -106,26 +155,61 @@ private static string GetPackagesAppearInFeedInOrderUrl(DateTime time, string ti
         /// <param name="packageIds">An ordered list of package ids. Each package id in the list must have a timestamp in the feed earlier than all package ids after it.</param>
         /// <param name="timestampPropertyName">The timestamp property to test the ordering of. For example, "Created" or "LastEdited".</param>
         /// <param name="operationStartTimestamp">A timestamp that is before all of the timestamps expected to be found in the feed. This is used in a request to the feed.</param>
+        /// <param name="packagesListed">Whether packages are listed, used to verify if latest flags are set properly.</param>
         private async Task CheckPackageTimestampsInOrder(List<string> packageIds, string timestampPropertyName,
-            DateTime operationStartTimestamp)
+            DateTime operationStartTimestamp, bool packagesListed)
```
Comment (scottbommarito) [inline tests/NuGetGallery.FunctionalTests/ODataFeeds/V2FeedExtendedTests.cs]: I like that you're adding this to my test as well as yours, but this parameter is unnecessary because you can determine whether or not the packages are listed based on the feed itself. If the package has a `Published` property that is greater than `DateTime.MinValue` (pretty sure it's January 1st 1900) then it is listed. You can parse this and then determine whether or not it should be latest or latest stable. I tried to do this initially but didn't realize that `Published` represented the listed status in the feed.

You could of course change this into a "expectListed" parameter that verifies that the listed status from the feed is identical to what we expect.

File: tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs (hunk 42 above)
Comment (chenriksson) [inline tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs]: I only switched to Task.CompletedTask for async methods w/o return values. Since TryUpdateIsLatestInDatabase returns Task<bool>, I want to return true to look like the db update was successful.

File: src/NuGetGallery/Services/PackageService.cs [hunk 45]
```diff
@@ -795,6 +795,7 @@ protected internal virtual IEntitiesContext CreateNewEntitiesContext()
                 int retryCount = 1;
                 do
                 {
+                    await Task.Delay(retryCount * 250);
```
Comment (skofman1) [inline src/NuGetGallery/Services/PackageService.cs]: to reduce the chance of retry collisions, I would recommend introducing randomization into the sleep duration
